### GET ALL
GET http://localhost:3001/api/shop


### ID
@id = 654ae0b11d3e2bb509c115e6

###GET ONE
GET http://localhost:3001/api/shop/{{id}}

### POST
# @name createShop
POST http://localhost:3001/api/shop
Content-Type: application/json
 
{
    "fantasyName": "Transporte DJJB",
    "address": "12 de Abril 0596",
    "billingType": "Resposable Inscripto",
    "mail": "djjb@gmail.com",
    "usualPaymentForm": "Efectivo",
    "type": "PyME",
    "contact": "654ad0d341b4fa27919f8af8",
    "owner": "654ada122beba8847bd81fa9"
}


###PUT 
PUT http://localhost:3001/api/shop/{{id}}
Content-Type: application/json 

{
    "fantasyName": "Transporte DJJB",
    "address": "12 de Abril 0596",
    "billingType": "Sin comprobante Fiscal",
    "mail": "djjb@gmail.com",
    "usualPaymentForm": "Efectivo",
    "type": "PyME"
}

#DUDA: en el PUT le tengo que pasar todos los atributos o 
# solo los que quiero cambiar?


### DELETE
DELETE http://localhost:3001/api/shop/654ae0b11d3e2bb509c115e6
