### GET ALL
GET http://localhost:3001/api/contract
   
  
### ID
@idShop = 6549b1cb9814910bc8096e11

@id = 654aefd5c3991db2b0d46152

###GET ONE
GET http://localhost:3001/api/contract/{{id}}

### POST
# @name createContract
POST http://localhost:3001/api/contract
Content-Type: application/json
 
 {
        "dateFrom" : "7/11/2023, 00:00:00",
        "dateTo" :"6/12/2023, 00:00:00",
        "observations" : "probando el manero de errores",
        "shop": "654ae5ac10991fd247130c51"
}



###PUT
PUT http://localhost:3001/api/contract/{{id}}
Content-Type: application/json 

{
    "dateFrom" : "7/11/2023, 00:00:00",
    "dateTo" :"6/12/2024, 00:00:00",
    "observations" : "",
    "shop": "654ae5ac10991fd247130c51"
    
}


### DELETE
DELETE http://localhost:3001/api/contract/65b978b0c76d436de401c5c0
