### GET ALL
GET http://localhost:3001/api/contract


### ID
@idShop = 6549b1cb9814910bc8096e11

@id = {{createContract.response.body.data.id}}

###GET ONE
GET http://localhost:3001/api/contract/{{id}}

### POST
# @name createContract
POST http://localhost:3001/api/contract
Content-Type: application/json
 
 {
        "dateFrom" : "7-11-2023",
        "dateTo" :"",
        "observations" : "quiere estar al final de la tanda.",
        "shop": "6549b1cb9814910bc8096e11"
}



###PUT
PUT http://localhost:3001/api/contract/{{id}}
Content-Type: application/json 

{
    "dateFrom" : "7-11-2023",
    "dateTo" :"7-12-2023",
    "observations" : "",
    "shop": "6549b10a4caaaa2d4d754510"
}


### DELETE
DELETE http://localhost:3001/api/contract/{{id}}
